from myMath import myArithmetic,myCalcArea,myStatistics
the_first_number=float(input('input your first number:'))
the_second_number=float(input('input your second number:'))
the_third_number=float(input('input your third number:'))
the_fourth_number=float(input('input your fourth number:'))
the_fifth_number=float(input('input your fifth number:'))
the_first_plus_the_second_number=myArithmetic.myAdd(the_first_number,the_second_number)
the_third_plus_the_fourth_number=myArithmetic.myAdd(the_third_number,the_fourth_number)
the_first_plus_the_second_plus_the_third_plus_the_fourth_number=myArithmetic.myAdd(the_first_plus_the_second_number,the_third_plus_the_fourth_number)
total_five_number=myArithmetic.myAdd(the_first_plus_the_second_plus_the_third_plus_the_fourth_number,the_fifth_number)
total_five_number_divise_five=myArithmetic.myDiv(total_five_number,5)
print(total_five_number_divise_five)
